name: Build and Commit LaTeX CV

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-extra latexmk

      - name: Prepare Build Directory
        run: |
          mkdir -p build
          cp src/altacv.cls build/  # Copy LaTeX class file to build directory
          cp -r src/themes build/ || true  # Copy themes if they exist

      - name: Compile CV
        run: |
          latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -output-directory=build src/content.tex
          mv build/content.pdf BALASCHSOLA.pdf  # Move compiled PDF to root

      - name: Commit PDF to Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add BALASCHSOLA.pdf
          git commit -m "🚀 Auto-update BALASCHSOLA.pdf" || echo "No changes to commit"
          git push